compile fix

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -1,10 +1,11 @@
 #!/bin/sh
 
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
-cd $SCRIPT_DIR/source/c++
+#cd $SCRIPT_DIR/source/c++
 
 echo "Compiling..."
-g++ -std=c++20 -Wextra -Wall -Werror -fexceptions -fno-common -D_GLIBCXX_ASSERTIONS -O3 *.cpp -o run
+g++ -std=c++20 -Wextra -Wall -Werror -fexceptions -fno-common -D_GLIBCXX_ASSERTIONS -O3 $SCRIPT_DIR/source/c++/*.cpp -o run
+#g++ -std=c++20 -Wextra -Wall -Werror -fexceptions -fno-common -D_GLIBCXX_ASSERTIONS -O3 *.cpp -o run
 
 # https://developers.redhat.com/blog/2018/03/21/compiler-and-linker-flags-gcc
 # -std=c++20: Specifies the C++ standard version whose features are requested to be enabled. The default, if no C++ language dialect options are given, is -std=gnu++98.
@@ -21,7 +22,8 @@ g++ -std=c++20 -Wextra -Wall -Werror -fexceptions -fno-common -D_GLIBCXX_ASSERTI
 # g++ -std=c++20 -Wextra -Wall -Werror -fexceptions -fno-common -D_GLIBCXX_ASSERTIONS -g3 *.cpp -o run
 #echo "Compiled successfully!"
 if [ $? -eq 0 ]; then
-  echo "Compilation successful. Output file: ../source/c++/run"
+  echo -e "\nCompilation successful. Output file: ../source/c++/run"
 else
-  echo "Compilation failed."
+  echo -e "\nCompilation failed."
+  exit 1
 fi
